INSERT INTO `topics`
(`id`, `background`, `parent`, `viewOrder`, `description`) VALUES
(   1,            0,        0,           1, 'Civil Liberties'                           ),
(   2,           55,        1,           1, 'Privacy'                                   ),
(   3,           89,        1,           2, 'Marriage'                                  ),
(   4,           83,        7,           1, 'Voting General'                            ),
(   5,           69,        1,           3, 'Stop And Frisk'                            ),
(   6,           56,        1,           4, 'Profiling'                                 ),
(   7,            0,        1,           5, 'Voting'                                    ),
(   8,           31,        7,           2, 'Identification Checks At Polling Places'   ),
(   9,           22,        7,           3, 'Felons And Voting'                         ),
(  10,           82,        7,           4, 'Two Party System'                          ),
(  11,          100,      105,           1, 'Abortion General'                          ),
(  12,           67,        7,           5, 'Standard Primary Vs Open Primary Elections'),
(  13,           42,        1,           6, 'Lgbt'                                      ),
(  14,            0,        0,           2, 'Crime And Punishment'                      ),
(  15,           53,       14,           1, 'Police'                                    ),
(  16,           58,       14,           2, 'Punishment'                                ),
(  17,            8,       14,           3, 'Civil Forfeiture'                          ),
(  18,           14,       14,           4, 'Crime Prevention'                          ),
(  19,            0,       14,           5, 'Judges'                                    ),
(  20,           90,       19,           1, 'Judges Experience'                         ),
(  21,           38,       19,           2, 'Judicial Election Rules'                   ),
(  22,           37,       19,           3, 'Judges And Political Activity'             ),
(  23,           35,       19,           4, 'Interpreting The Law'                      ),
(  24,           58,       19,           5, 'Punishment'                                ),
(  25,           44,       19,           6, 'Mandatory Sentencing'                      ),
(  26,            0,       19,           7, 'Citizens United'                           ),
(  27,            0,       19,           8, 'Search And Seizure'                        ),
(  28,            0,       19,           9, 'Second Ammendment'                         ),
(  29,            0,        0,           3, 'Education'                                 ),
(  30,            0,       29,           1, 'Priorities'                                ),
(  31,            0,       29,           2, 'General Education'                         ),
(  32,            0,       29,           3, 'Health Education'                          ),
(  33,            0,       29,           4, 'Stress Management Education'               ),
(  34,           66,       29,           5, 'Stability'                                 ),
(  35,           68,       29,           6, 'Standardized Tests'                        ),
(  36,           71,       29,           7, 'Summer Recess'                             ),
(  37,            0,        0,           5, 'Environment'                               ),
(  38,           19,       37,           1, 'General'                                   ),
(  39,            0,       37,           2, 'Water'                                     ),
(  40,            0,       37,           3, 'Air'                                       ),
(  41,           26,       37,           4, 'Global Warming'                            ),
(  42,           40,       37,           5, 'Land'                                      ),
(  43,            0,       42,           1, 'Farming'                                   ),
(  44,            2,       42,           2, 'Bees'                                      ),
(  45,           62,       42,           3, 'Safe Farm Practices'                       ),
(  46,           88,       42,           4, 'GMO0s (Genetically modified Organisms)'    ),
(  47,            0,       37,           6, 'Plants and Animals'                        ),
(  48,            0,        0,           4, 'Energy'                                    ),
(  49,            0,       48,           1, 'General'                                   ),
(  50,           12,       48,           2, 'Conservation And Increased Efficiency'     ),
(  51,            5,       48,           3, 'Carbon Cap And Trade'                      ),
(  52,           24,       48,           4, 'Fracking'                                  ),
(  53,           49,       48,           5, 'Oil'                                       ),
(  54,           10,       48,           6, 'Coal'                                      ),
(  55,           47,       48,           7, 'Natural Gas'                               ),
(  56,           48,       48,           8, 'Nuclear Power'                             ),
(  57,           86,       48,           9, 'Wind'                                      ),
(  58,           64,       48,          10, 'Solar'                                     ),
(  59,            0,       48,          11, 'Favorites'                                 ),
(  60,            0,        0,          10, 'Foreign Policy'                            ),
(  61,           96,       60,           1, 'Military Foreign Policy'                   ),
(  62,           97,       60,           2, 'Economic Foreign Policy'                   ),
(  63,           77,       60,           3, 'The Middle East'                           ),
(  64,           78,       60,           4, 'The Undeveloped Third World Nations'       ),
(  65,            0,        0,           6, 'Gun Control'                               ),
(  66,            0,        0,           7, 'Healthcare And Safety'                     ),
(  67,           29,       66,           1, 'Billing Under Current System'              ),
(  68,           80,       66,           2, 'Tort Reform'                               ),
(  69,           46,       66,           3, 'Nationalized Healthcare'                   ),
(  70,            3,       66,           4, 'Benefits For Part Time Workers'            ),
(  71,           59,       66,           5, 'Quality Of Care'                           ),
(  72,           76,       66,           6, 'Testing On Children'                       ),
(  73,           98,       66,           7, 'Cost Of Drugs'                             ),
(  74,           87,       66,           8, 'Generic Drugs'                             ),
(  75,           99,       66,           9, 'End Of Life Issues'                        ),
(  76,            0,        0,           8, 'Immigration'                               ),
(  77,           91,       76,           1, 'Legal And Illegal Immigration'             ),
(  78,           32,       76,           2, 'Illegal Immigration'                       ),
(  79,           41,       76,           3, 'Legal Immigration'                         ),
(  80,           92,       76,           4, 'Multi-Lingual Services'                    ),
(  81,           93,       76,           5, 'Services For Undocumented (Illegal) Immigrants'),
(  82,            0,        0,           9, 'Infrastructure'                            ),
(  83,           34,       82,           1, 'General'                                   ),
(  84,           94,       82,           2, 'Privatizing'                               ),
(  85,           17,       82,           3, 'Eminent Domain'                            ),
(  86,           61,       82,           4, 'Roads And Bridges'                         ),
(  87,           50,       82,           5, 'Parking'                                   ),
(  88,           57,       82,           6, 'Public Transit'                            ),
(  89,           11,       82,           7, 'Communications'                            ),
(  90,           25,       82,           8, 'Gas Lines'                                 ),
(  91,           54,       82,           9, 'Power Lines'                               ),
(  92,           63,       82,          10, 'Sewage System'                             ),
(  93,           85,       82,          11, 'Water Supply'                              ),
(  94,            0,        0,          11, 'Jobs And The Economy'                      ),
(  95,           13,       94,           1, 'Consumer Confidence'                       ),
(  96,           51,       94,           2, 'Patents'                                   ),
(  97,           15,       94,           3, 'Digital Millenium Copyright Act And Fair Use Act'),
(  98,           45,        0,          12, 'Military'                                  ),
(  99,           81,       98,           1, 'Torture'                                   ),
( 100,           95,       98,           2, 'Use of Animals in War'                     ),
( 101,          102,       98,           3, 'Miscellaneous'                             ),
( 102,            0,        0,          13, 'Reproduction'                              ),
( 103,            6,      102,           1, 'Child Rearing'                             ),
( 104,            4,      102,           2, 'Birth Control'                             ),
( 105,            0,        0,            0, 'Abortion'                                  ),
( 106,           79,      105,           2, 'Third Trimester Abortions'                 ),
( 107,           16,      102,           3, 'Emergency Contraception'                   ),
( 108,            0,        0,          12, 'Quality Of Life'                           ),
( 109,           43,      108,           0, 'Libraries'                                 ),
( 110,           60,      108,           0, 'Quality Of Life Crimes'                    ),
( 111,            0,      108,           0, 'Retirement'                                ),
( 112,          103,      111,           0, 'Driving'                                   ),
( 113,          104,      111,           0, 'Retirement Age'                            ),
( 114,            0,        0,          14, 'Taxes'                                     ),
( 115,            0,      114,           0, 'General'                                   ),
( 116,            0,      114,           0, 'Estate Tax'                                ),
( 117,           73,      114,           0, 'Tax Incentives'                            ),
( 118,           72,      114,           0, 'Tax Disincentives'                         ),
( 119,           65,      114,           0, 'Specific Taxes And Programs'               ),
( 120,           33,      114,           0, 'Increasing Revenue Without Taxing'         ),
( 121,           74,      114,           0, 'Tax Reform'                                ),
( 122,            0,        0,          15, 'Social Services'                           ),
( 123,           30,      122,           0, 'Housing Programs: Hud/Section 8'           ),
( 124,           23,      122,           0, 'Food Stamps/Snap (Supplemental Nutrition Assistance Program)'),
( 125,          105,      122,           0, 'Disaster Services'                         ),
( 126,          106,      122,           0, 'Domestic Violence'                         ),
( 127,          107,      122,           0, 'Addiction'                                 ),
( 128,          108,      122,           0, 'Breakfast/Lunch'                           ),
( 129,          109,      122,           0, 'Mental Health'                             ),
( 130,            0,      122,           0, 'Welfare'                                   ),
( 131,          110,      122,           0, 'Social Security'                           ),
( 132,          111,      122,           0, 'Medicaid'                                  ),
( 133,          112,      122,           0, 'Medicare'                                  ),
( 134,          113,      122,           0, 'Child Welfare'                             ),
( 135,          114,      122,           0, 'Wic (Women Infants And Children)'          ),
( 136,            0,      122,           0, 'Unemployment/Retraining'                   ),
( 137,            0,      122,           0, 'Consumer Advocacy'                         ),
( 138,            0,      122,           0, 'Ada  Disability'                           ),
( 139,            0,      122,           0, 'Aging   Fire Alarms, Emergency, Phones'    ),
( 140,            0,      122,           0, 'Sexuality Education'                       ),
( 141,            0,      122,           0, 'Emergency Shelter/Housing'                 ),
( 142,            0,      122,           0, 'General Local Questions'                   ),
( 143,           52,       47,           1, 'Plant and Animals General'                 ),
( 144,          101,        0,           0, 'Land Mines'                                ),
( 145,          115,        0,           0, 'Home Made Guns'                            ),
( 146,           27,        0,           0, 'Gun Control General'                       );

